name: dribbble_challenge
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.4.0
  freezed: ^3.0.6
  shared_preferences: ^2.2.1
  timelines_plus: ^1.0.7
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  sliding_up_panel: ^2.0.0+1
  flex_color_scheme: ^8.2.0
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_lint: ^2.0.4
  custom_lint: ^0.7.5
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/recipes.json
    - assets/images/

